"""informations_notifications

Revision ID: 20260912_08
Revises: 20260911_07
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260912_08"
down_revision: str | Sequence[str] | None = "20260911_07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DIET_UPDATED",
                "WORKOUT_UPDATED",
                "REEVALUATION_CREATED",
                "REEVALUATION_IN_REVIEW",
                "REEVALUATION_COMPLETED",
                "REEVALUATION_CANCELLED",
                "INFORMATION_PUBLISHED",
                "STUDENT_PENDING_APPROVAL",
                name="notification_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "DIET_VERSION",
                "WORKOUT_VERSION",
                "REEVALUATION",
                "INFORMATION",
                "STUDENT",
                name="notification_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "type", "resource_id", name="uq_notification_event_recipient"
        ),
    )
    op.create_index(
        "ix_notification_unread_user",
        "notifications",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "ix_notification_user_created",
        "notifications",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "informations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "INFO",
                "TIP",
                "NOTICE",
                "GUIDANCE",
                name="information_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="information_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("edit_revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("edit_revision > 0", name="ck_information_revision"),
        sa.CheckConstraint(
            "length(trim(content)) BETWEEN 10 AND 10000", name="ck_information_content"
        ),
        sa.CheckConstraint("length(trim(title)) BETWEEN 3 AND 160", name="ck_information_title"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["professional_id"], ["professionals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_information_portfolio_status_date",
        "informations",
        ["professional_id", "status", "published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_informations_student_id"), "informations", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_informations_student_id"), table_name="informations")
    op.drop_index("ix_information_portfolio_status_date", table_name="informations")
    op.drop_table("informations")
    op.drop_index("ix_notification_user_created", table_name="notifications")
    op.drop_index(
        "ix_notification_unread_user",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notifications")
    # ### end Alembic commands ###
